# Generated by Django 5.2 on 2026-02-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="poster_last_read",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="volunteer_last_read",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
