# Generated by Django 5.2 on 2026-02-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0004_alter_jobacceptance_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="location_label",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_location_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="location_label",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="location_source",
            field=models.CharField(
                choices=[("gps", "GPS"), ("manual", "Manual")],
                default="manual",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="max_distance_miles",
            field=models.IntegerField(default=25),
        ),
    ]
